<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
<script>
    // 执行结果：会继续打印输出，promise内部的报错数据不会影响到promise外部
    const someAsyncThing = function () {
        return new Promise( (resolve , reject) => {
            resolve(x+2);
        } )
    };
    someAsyncThing().then( (res) => {
        console.log(res);
    } );

    setTimeout( ()=>{ console.log("是否阻止了进程") } , 3000 );
</script>
</html>